name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: Describe the feature or improvement.
      placeholder: "It would be great if Zoebox could..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why?
      description: What problem does this solve for you?
      placeholder: "Currently I have to..."
    validations:
      required: false
